apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aitpg.fullname" . }}-secrets
  labels:
    {{- include "aitpg.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
